site_name: CV 2015
theme_dir: ../../cv/style
site_author: matt
site_dir: ../../../site
docs_dir: ../../cv
pages:
- Abbreviated CV: 'cv.md'
- Detailed Work Experience: 'work.md'
- Projects, Demos, Code Samples: 'projects.md'
- Diagrams, Docs Samples: 'samples.md'